# Getting Started with TensorFlow

In [1]:
import tensorflow as tf

### Into to `tf` `Variable`,  `constant` and  `placeholders`

#### TensorFlow Variable `tf.Variable`

In [2]:
a = tf.Variable(3, name="a")
b = tf.Variable(2, name="y")
f = a**2 + 2*a*b + b**2

In [3]:
a

<tf.Variable 'a:0' shape=() dtype=int32_ref>

In [4]:
f

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [5]:
with tf.Session() as sess:
    a.initializer.run()
    b.initializer.run()
    result = f.eval()

In [6]:
print(result)
sess.close()

25


In [7]:
i = tf.Variable(0, name="i")
ops = tf.assign(i, i+2)
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    val = sess.run(i)
    print(val)
    for _ in range(5):
        sess.run(ops)
        print(sess.run(i))

sess.close()

0
2
4
6
8
10


#### TensorFlow constant `tf.constant`

In [8]:
x = tf.constant(7, name="x")
y = tf.constant(5, name="y")
z = tf.add(x, y)

In [9]:
x

<tf.Tensor 'x:0' shape=() dtype=int32>

In [10]:
z

<tf.Tensor 'Add_3:0' shape=() dtype=int32>

In [11]:
with tf.Session() as sess:
    add = sess.run(z)

In [12]:
print(add)

12


#### TensorFlow Placeholders `tf.placeholders`

In [13]:
tf.reset_default_graph()

In [14]:
X = tf.placeholder(tf.int32)
y = X ** 2
dct = {X:[[2,5,7],[5,7,4],[0,5,7]]}
with tf.Session() as sess:
    result = sess.run(y,feed_dict=dct)
    print(result)

[[ 4 25 49]
 [25 49 16]
 [ 0 25 49]]


# Into to Graph
 Let's create our very first TensorFlow Graph `tf.Graph()`

In [15]:
Graph = tf.Graph()

In [16]:
Graph

In [17]:
with Graph.as_default():
    a = tf.constant([5], name="const_a")
    b = tf.constant([3], name="const_b")
    c = tf.add(a, b)

In [18]:
b

<tf.Tensor 'const_b:0' shape=(1,) dtype=int32>

In [19]:
c

<tf.Tensor 'Add:0' shape=(1,) dtype=int32>

In [20]:
sess = tf.Session(graph = Graph)
result = sess.run(b)
print("C :",result)

C : [3]


In [21]:
sess.close()

In [22]:
sess = tf.Session(graph = Graph)

In [23]:
sess.run(c)

array([8])

In [24]:
sess.close()

In [25]:
with tf.Session(graph=Graph) as sess:
    add_result = sess.run(c)
    print(add_result)

[8]


# Defining Tensor
Let's define multidimensional arrays(Tensor) using TensorFlow

In [26]:
tf.reset_default_graph()

In [27]:
graph = tf.Graph()
with graph.as_default():
    dim_0 = tf.constant(2, name="Scalar")
    dim_1 = tf.constant([1,2,3], name="Vector")
    dim_2 = tf.constant([[1,2,3],[4,5,6],[7,8,9]], name="Matrix")
    dim_3 = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]], 
                           [[4,5,6],[5,6,7],[6,7,8]], 
                           [[7,8,9],[8,9,10],[9,10,11]]
                         ], name="Tensor")

In [28]:
with tf.Session(graph=graph) as sess:
    def sess_run(tensor):
        value = sess.run(tensor)
        print(tensor)
        print("Value of Tensor :",value)
        print("\n")
    
    sess_run(dim_0)
    sess_run(dim_1)
    sess_run(dim_2)
    sess_run(dim_3)

Tensor("Scalar:0", shape=(), dtype=int32)
Value of Tensor : 2


Tensor("Vector:0", shape=(3,), dtype=int32)
Value of Tensor : [1 2 3]


Tensor("Matrix:0", shape=(3, 3), dtype=int32)
Value of Tensor : [[1 2 3]
 [4 5 6]
 [7 8 9]]


Tensor("Tensor:0", shape=(3, 3, 3), dtype=int32)
Value of Tensor : [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]




# Tensor Operations

In [29]:
tf.reset_default_graph()

In [30]:
graph = tf.Graph()

with graph.as_default():
    x = tf.constant([[1,2,1],[3,2,4],[5,3,4]], name="const_x")
    y = tf.constant([[4,3,7],[5,4,5],[7,4,7]], name="const_y")
    
    add = x + y
    add_ops = tf.add(x, y)
    matmul = tf.matmul(x, y)

In [31]:
with tf.Session(graph=graph) as sess:
    result_add = sess.run(add)
    result_add_ops = sess.run(add_ops)
    result_matmul = sess.run(matmul)
    print("Add :\n", result_add)
    print("\n")
    print("Add with tf ops :\n", result_add_ops)
    print("\n")
    print("Matrix Multiplication with tf ops\n", result_matmul)

Add :
 [[ 5  5  8]
 [ 8  6  9]
 [12  7 11]]


Add with tf ops :
 [[ 5  5  8]
 [ 8  6  9]
 [12  7 11]]


Matrix Multiplication with tf ops
 [[21 15 24]
 [50 33 59]
 [63 43 78]]
